language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite
  APP_KEY: b4f02ccc59f38233cdd984353a279f10
  BROADCAST_DRIVER: log

branches:
  - master

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 9.11.2
  - nvm use 9.11.2
  - npm install -g yarn
  - yarn
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - composer test
  - yarn lint
